version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mediscreen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mediscreen:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mediscreen
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"
volumes:
  pgdata: